### ISSUE TITLE
How to find session start time ?

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/ixnetwork_restpy#35]
Hi, 

I'm trying to use statistics CSV logging. Because timestamps in result csv file seems to count from session start I need to find sessions start time to get usable timestamps.

I tried the following code (it's based on sample from docs)
```
from ixnetwork_restpy import TestPlatform

tpl = TestPlatform('10.10.0.222', 11029)
ixnetwork = tpl.Sessions.find().Ixnetwork
tl = ixnetwork.Timeline
print(tl.StartTime)
```

but it gives me NotFoundError
```
ixnetwork_restpy.errors.NotFoundError: The attribute startTime is not in the internal list of object dicts. 
            If there is a find method execute that prior to executing a property accessor.
            Check the number of encapsulated resources using the len method.
            list index out of range
```

I'm using IxNetwork 9.10.2007.7 and ixnetwork_restpy 1.0.59. 
I appreciate any clues.

**Comment by therkong** [comment]
RestPy currently does not have the session start time info.
If you do https GET on the session, you do have the start time info.
   
Alternatively, you can set the IxNet API Server to use system clock.  
In order to set timestamps on CSV logs to local time, please enable the following option:

![image](https://user-images.githubusercontent.com/35854929/103680602-40936b80-4f3b-11eb-9634-ba23bf5a2beb.png)

**Comment by therkong** [comment]
For CSV Logging, please configure the API Server session to use the system clock instead of the start time of the session.     Below is the code snip to set it:

from ixnetwork_restpy import TestPlatform

statistics = TestPlatform('127.0.0.1') \
.Sessions.find() \
.Ixnetwork \
.Statistics
print(statistics.TimeSynchronization)
statistics.TimeSynchronization = 'syncTimeToSystemClock'
